package com.vanroid.gd.shop.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("gd_admin", "id", GdAdmin.class);
		arp.addMapping("gd_book", "bookId", GdBook.class);
		arp.addMapping("gd_circle", "tid", GdCircle.class);
		arp.addMapping("gd_circleimg", "pid", GdCircleimg.class);
		arp.addMapping("gd_circlemes", "mid", GdCirclemes.class);
		arp.addMapping("gd_class", "classId", GdClass.class);
		arp.addMapping("gd_club", "id", GdClub.class);
		arp.addMapping("gd_club_message", "id", GdClubMessage.class);
		arp.addMapping("gd_comment", "cid", GdComment.class);
		arp.addMapping("gd_course", "cid", GdCourse.class);
		arp.addMapping("gd_grade", "gid", GdGrade.class);
		// Composite Primary Key order: gid,sid
		arp.addMapping("gd_grade_middle", "gid,sid", GdGradeMiddle.class);
		arp.addMapping("gd_lfcomment", "lfcId", GdLfcomment.class);
		arp.addMapping("gd_library_book", "bookId", GdLibraryBook.class);
		arp.addMapping("gd_library_search_history", "id", GdLibrarySearchHistory.class);
		arp.addMapping("gd_message", "mid", GdMessage.class);
		arp.addMapping("gd_offer", "id", GdOffer.class);
		arp.addMapping("gd_subject", "sid", GdSubject.class);
		arp.addMapping("gd_user", "id", GdUser.class);
	}
}

