package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdAdmin extends BaseGdAdmin<GdAdmin> {
	public static final GdAdmin dao = new GdAdmin();
}
