package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdBook extends BaseGdBook<GdBook> {
	public static final GdBook dao = new GdBook();
}
