package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdCircleimg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdCircleimg extends BaseGdCircleimg<GdCircleimg> {
	public static final GdCircleimg dao = new GdCircleimg();
}
