package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdCirclemes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdCirclemes extends BaseGdCirclemes<GdCirclemes> {
	public static final GdCirclemes dao = new GdCirclemes();
}
