package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdCircle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdCircle extends BaseGdCircle<GdCircle> {
	public static final GdCircle dao = new GdCircle();
}
