package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdClass extends BaseGdClass<GdClass> {
	public static final GdClass dao = new GdClass();
}
