package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdClub;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdClub extends BaseGdClub<GdClub> {
	public static final GdClub dao = new GdClub();
}
