package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdClubMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdClubMessage extends BaseGdClubMessage<GdClubMessage> {
	public static final GdClubMessage dao = new GdClubMessage();
}
