package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdComment extends BaseGdComment<GdComment> {
	public static final GdComment dao = new GdComment();
}
