package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdCourse extends BaseGdCourse<GdCourse> {
	public static final GdCourse dao = new GdCourse();
}
