package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdGradeMiddle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdGradeMiddle extends BaseGdGradeMiddle<GdGradeMiddle> {
	public static final GdGradeMiddle dao = new GdGradeMiddle();
}
