package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdGrade extends BaseGdGrade<GdGrade> {
	public static final GdGrade dao = new GdGrade();
}
