package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdLfcomment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdLfcomment extends BaseGdLfcomment<GdLfcomment> {
	public static final GdLfcomment dao = new GdLfcomment();
}
