package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdLibrarySearchHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdLibrarySearchHistory extends BaseGdLibrarySearchHistory<GdLibrarySearchHistory> {
	public static final GdLibrarySearchHistory dao = new GdLibrarySearchHistory();
}
