package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdLibraryBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdLibraryBook extends BaseGdLibraryBook<GdLibraryBook> {
	public static final GdLibraryBook dao = new GdLibraryBook();
}
