package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdMessage extends BaseGdMessage<GdMessage> {
	public static final GdMessage dao = new GdMessage();
}
