package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdOffer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdOffer extends BaseGdOffer<GdOffer> {
	public static final GdOffer dao = new GdOffer();
}
