package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdSubject extends BaseGdSubject<GdSubject> {
	public static final GdSubject dao = new GdSubject();
}
