package com.vanroid.gd.shop.model;

import com.vanroid.gd.shop.model.base.BaseGdUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GdUser extends BaseGdUser<GdUser> {
	public static final GdUser dao = new GdUser();
}
