package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdCourse<M extends BaseGdCourse<M>> extends Model<M> implements IBean {

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}

	public java.lang.Integer getCid() {
		return get("cid");
	}

	public void setStuId(java.lang.String stuId) {
		set("stuId", stuId);
	}

	public java.lang.String getStuId() {
		return get("stuId");
	}

	public void setXq(java.lang.Integer xq) {
		set("xq", xq);
	}

	public java.lang.Integer getXq() {
		return get("xq");
	}

	public void setYear(java.lang.String year) {
		set("year", year);
	}

	public java.lang.String getYear() {
		return get("year");
	}

}
