package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdUser<M extends BaseGdUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccessTimes(java.lang.Integer accessTimes) {
		set("accessTimes", accessTimes);
	}

	public java.lang.Integer getAccessTimes() {
		return get("accessTimes");
	}

	public void setClassId(java.lang.String classId) {
		set("classId", classId);
	}

	public java.lang.String getClassId() {
		return get("classId");
	}

	public void setComfirmPassword(java.lang.String comfirmPassword) {
		set("comfirmPassword", comfirmPassword);
	}

	public java.lang.String getComfirmPassword() {
		return get("comfirmPassword");
	}

	public void setDepart(java.lang.String depart) {
		set("depart", depart);
	}

	public java.lang.String getDepart() {
		return get("depart");
	}

	public void setHeadImg(java.lang.String headImg) {
		set("headImg", headImg);
	}

	public java.lang.String getHeadImg() {
		return get("headImg");
	}

	public void setJwcPass(java.lang.String jwcPass) {
		set("jwcPass", jwcPass);
	}

	public java.lang.String getJwcPass() {
		return get("jwcPass");
	}

	public void setLibaryPass(java.lang.String libaryPass) {
		set("libaryPass", libaryPass);
	}

	public java.lang.String getLibaryPass() {
		return get("libaryPass");
	}

	public void setMarjor(java.lang.String marjor) {
		set("marjor", marjor);
	}

	public java.lang.String getMarjor() {
		return get("marjor");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setRealName(java.lang.String realName) {
		set("realName", realName);
	}

	public java.lang.String getRealName() {
		return get("realName");
	}

	public void setRegistDate(java.util.Date registDate) {
		set("registDate", registDate);
	}

	public java.util.Date getRegistDate() {
		return get("registDate");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setStuId(java.lang.String stuId) {
		set("stuId", stuId);
	}

	public java.lang.String getStuId() {
		return get("stuId");
	}

	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}

	public java.lang.String getTelphone() {
		return get("telphone");
	}

	public void setXnMailPass(java.lang.String xnMailPass) {
		set("xnMailPass", xnMailPass);
	}

	public java.lang.String getXnMailPass() {
		return get("xnMailPass");
	}

}
