package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdClub<M extends BaseGdClub<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClubName(java.lang.String clubName) {
		set("club_name", clubName);
	}

	public java.lang.String getClubName() {
		return get("club_name");
	}

	public void setClubPhoto(java.lang.String clubPhoto) {
		set("club_photo", clubPhoto);
	}

	public java.lang.String getClubPhoto() {
		return get("club_photo");
	}

	public void setClubSetup(java.util.Date clubSetup) {
		set("club_setup", clubSetup);
	}

	public java.util.Date getClubSetup() {
		return get("club_setup");
	}

	public void setClubState(java.lang.Integer clubState) {
		set("club_state", clubState);
	}

	public java.lang.Integer getClubState() {
		return get("club_state");
	}

	public void setClubSummary(java.lang.String clubSummary) {
		set("club_summary", clubSummary);
	}

	public java.lang.String getClubSummary() {
		return get("club_summary");
	}

	public void setClubVerification(java.lang.String clubVerification) {
		set("club_verification", clubVerification);
	}

	public java.lang.String getClubVerification() {
		return get("club_verification");
	}

	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}

	public java.lang.Integer getAdminId() {
		return get("admin_id");
	}

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}

	public java.lang.Integer getCid() {
		return get("cid");
	}

	public void setCIcon(java.lang.String cIcon) {
		set("cIcon", cIcon);
	}

	public java.lang.String getCIcon() {
		return get("cIcon");
	}

	public void setCName(java.lang.String cName) {
		set("cName", cName);
	}

	public java.lang.String getCName() {
		return get("cName");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setCdescribe(java.lang.String cdescribe) {
		set("cdescribe", cdescribe);
	}

	public java.lang.String getCdescribe() {
		return get("cdescribe");
	}

	public void setClubNum(java.lang.String clubNum) {
		set("clubNum", clubNum);
	}

	public java.lang.String getClubNum() {
		return get("clubNum");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setAid(java.lang.Integer aid) {
		set("aid", aid);
	}

	public java.lang.Integer getAid() {
		return get("aid");
	}

}
