package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdGradeMiddle<M extends BaseGdGradeMiddle<M>> extends Model<M> implements IBean {

	public void setGid(java.lang.Integer gid) {
		set("gid", gid);
	}

	public java.lang.Integer getGid() {
		return get("gid");
	}

	public void setSid(java.lang.Integer sid) {
		set("sid", sid);
	}

	public java.lang.Integer getSid() {
		return get("sid");
	}

}
