package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdClubMessage<M extends BaseGdClubMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMessageContent(java.lang.String messageContent) {
		set("message_content", messageContent);
	}

	public java.lang.String getMessageContent() {
		return get("message_content");
	}

	public void setMessagePhoto(java.lang.String messagePhoto) {
		set("message_photo", messagePhoto);
	}

	public java.lang.String getMessagePhoto() {
		return get("message_photo");
	}

	public void setMessagePublishdate(java.util.Date messagePublishdate) {
		set("message_publishdate", messagePublishdate);
	}

	public java.util.Date getMessagePublishdate() {
		return get("message_publishdate");
	}

	public void setMessageState(java.lang.Integer messageState) {
		set("message_state", messageState);
	}

	public java.lang.Integer getMessageState() {
		return get("message_state");
	}

	public void setMessageTitle(java.lang.String messageTitle) {
		set("message_title", messageTitle);
	}

	public java.lang.String getMessageTitle() {
		return get("message_title");
	}

	public void setClubId(java.lang.Integer clubId) {
		set("club_id", clubId);
	}

	public java.lang.Integer getClubId() {
		return get("club_id");
	}

}
