package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdOffer<M extends BaseGdOffer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOfferContent(java.lang.String offerContent) {
		set("offer_content", offerContent);
	}

	public java.lang.String getOfferContent() {
		return get("offer_content");
	}

	public void setOfferPhoto1(java.lang.String offerPhoto1) {
		set("offer_photo1", offerPhoto1);
	}

	public java.lang.String getOfferPhoto1() {
		return get("offer_photo1");
	}

	public void setOfferPhoto2(java.lang.String offerPhoto2) {
		set("offer_photo2", offerPhoto2);
	}

	public java.lang.String getOfferPhoto2() {
		return get("offer_photo2");
	}

	public void setOfferPhoto3(java.lang.String offerPhoto3) {
		set("offer_photo3", offerPhoto3);
	}

	public java.lang.String getOfferPhoto3() {
		return get("offer_photo3");
	}

	public void setOfferPublishtime(java.util.Date offerPublishtime) {
		set("offer_publishTime", offerPublishtime);
	}

	public java.util.Date getOfferPublishtime() {
		return get("offer_publishTime");
	}

	public void setOfferTitle(java.lang.String offerTitle) {
		set("offer_title", offerTitle);
	}

	public java.lang.String getOfferTitle() {
		return get("offer_title");
	}

}
