package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdLibrarySearchHistory<M extends BaseGdLibrarySearchHistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}

	public java.lang.String getKeywords() {
		return get("keywords");
	}

	public void setPage(java.lang.Integer page) {
		set("page", page);
	}

	public java.lang.Integer getPage() {
		return get("page");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

}
