package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdBook<M extends BaseGdBook<M>> extends Model<M> implements IBean {

	public void setBookId(java.lang.Integer bookId) {
		set("bookId", bookId);
	}

	public java.lang.Integer getBookId() {
		return get("bookId");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public void setBorrowableCount(java.lang.Integer borrowableCount) {
		set("borrowableCount", borrowableCount);
	}

	public java.lang.Integer getBorrowableCount() {
		return get("borrowableCount");
	}

	public void setDpt(java.lang.Integer dpt) {
		set("dpt", dpt);
	}

	public java.lang.Integer getDpt() {
		return get("dpt");
	}

	public void setHref(java.lang.String href) {
		set("href", href);
	}

	public java.lang.String getHref() {
		return get("href");
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return get("number");
	}

	public void setPress(java.lang.String press) {
		set("press", press);
	}

	public java.lang.String getPress() {
		return get("press");
	}

	public void setPressDate(java.lang.String pressDate) {
		set("pressDate", pressDate);
	}

	public java.lang.String getPressDate() {
		return get("pressDate");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

}
