package com.vanroid.gd.shop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGdLfcomment<M extends BaseGdLfcomment<M>> extends Model<M> implements IBean {

	public void setLfcId(java.lang.Integer lfcId) {
		set("lfcId", lfcId);
	}

	public java.lang.Integer getLfcId() {
		return get("lfcId");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setLfcDate(java.util.Date lfcDate) {
		set("lfcDate", lfcDate);
	}

	public java.util.Date getLfcDate() {
		return get("lfcDate");
	}

	public void setMid(java.lang.Integer mid) {
		set("mid", mid);
	}

	public java.lang.Integer getMid() {
		return get("mid");
	}

}
